version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: adspace
      POSTGRES_USER: adspace
      POSTGRES_PASSWORD: adspace123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adspace"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Rust Backend API
  adspace-backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://adspace:adspace123@postgres:5432/adspace
      PORT: 3001
      HOST: 0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/app/migrations
    restart: unless-stopped

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
